// AUTO-GENERIERT von scripts/normtext/kanton-abk-aliase-generieren.ts — NICHT von Hand editieren.
// Amtlich belegte Kürzel der Kanton-Erlasse (abbreviation-Feld der kantonalen
// Erlasssammlungs-APIs, projiziert über public/normtext/register.json).
// Ausschluss-Regeln R1–R5 + Klammer-Verzicht: Kopf des Generators (§7, nie erfinden).
// 572 Aliase über 20 Kantone · ausgeschlossen: kleinwoerter 9 · titel-kopie 49 · zu-lang 601.
// Kürzel ist ALIAS, nie Schlüssel: dasselbe abk darf auf mehrere Erlasse zeigen
// (kantonsübergreifend wie innerhalb eines Kantons); Bund↔Kanton-Kollisionen sind
// legitim und im Report bibliothek/register/kanton-abk-kollisionen-*.md dokumentiert.
// Regenerieren: npm run gen:kanton-abk-aliase · Drift: npm run check:kanton-abk-aliase
// NICHT aus src/ importieren (Bundle §15) — Build-Zeit-Quelle für such-index-generieren.ts
// (Feld kz) und scripts/datenhaltung/fts.ts (FTS-Spalte kuerzel).

export const KANTON_ABK_ALIASE: ReadonlyArray<{ abk: string; kanton: string; key: string }> = [
  { abk: "AB", kanton: "BS", key: "BS-152.110" },
  { abk: "AB IWB Datenbearbeitung", kanton: "BS", key: "BS-772.380" },
  { abk: "ABPV", kanton: "BS", key: "BS-730.115" },
  { abk: "ABRG", kanton: "AR", key: "AR-621.12" },
  { abk: "ABVV", kanton: "BS", key: "BS-212.200" },
  { abk: "ALHG", kanton: "BS", key: "BS-835.500" },
  { abk: "ALHV", kanton: "BS", key: "BS-835.510" },
  { abk: "ANöRV", kanton: "BS", key: "BS-724.115" },
  { abk: "AO", kanton: "BS", key: "BS-BaB 162.100" },
  { abk: "ASV", kanton: "BS", key: "BS-786.150" },
  { abk: "AV", kanton: "BS", key: "BS-497.120" },
  { abk: "AWV", kanton: "AR", key: "AR-920.13" },
  { abk: "AZV", kanton: "BS", key: "BS-162.200" },
  { abk: "Abfallordnung", kanton: "BS", key: "BS-BeE 786.100" },
  { abk: "Abfallordnung", kanton: "BS", key: "BS-RiE 786.100" },
  { abk: "Abfallvereinbarung BS - BL", kanton: "BS", key: "BS-786.300" },
  { abk: "Abfallverordnung", kanton: "BS", key: "BS-786.100" },
  { abk: "Abschlussverordnung FMS", kanton: "BS", key: "BS-413.630" },
  { abk: "Advokaturgesetz", kanton: "BS", key: "BS-291.100" },
  { abk: "AfWW beider Basel", kanton: "BS", key: "BS-911.700" },
  { abk: "Alkohol- und Drogengesetz", kanton: "BS", key: "BS-322.100" },
  { abk: "Allmendordnung", kanton: "BS", key: "BS-RiE 724.100" },
  { abk: "Allmendreglement", kanton: "BS", key: "BS-RiE 724.150" },
  { abk: "Allmendverordnung", kanton: "BS", key: "BS-724.140" },
  { abk: "Amerbach-Preis", kanton: "BS", key: "BS-494.400" },
  { abk: "Anerkennungsprämien-Verordnung", kanton: "BS", key: "BS-164.200" },
  { abk: "AnwHV", kanton: "AI", key: "AI-177.410" },
  { abk: "AnwT", kanton: "TG", key: "TG-176.31" },
  { abk: "AnwT", kanton: "ZG", key: "ZG-163.4" },
  { abk: "Anwaltsgesetz", kanton: "AR", key: "AR-145.52" },
  { abk: "Anwaltstarif", kanton: "AG", key: "AG-291.150" },
  { abk: "Arbeitsgesetz", kanton: "BS", key: "BS-812.100" },
  { abk: "Archivgesetz", kanton: "AR", key: "AR-421.10" },
  { abk: "Archivgesetz", kanton: "BS", key: "BS-153.600" },
  { abk: "Archivierungsreglement", kanton: "BS", key: "BS-154.118" },
  { abk: "Assekuranzgesetz", kanton: "AR", key: "AR-862.1" },
  { abk: "Assekuranzverordnung", kanton: "AR", key: "AR-862.11" },
  { abk: "Asylvertrag", kanton: "BS", key: "BS-890.800" },
  { abk: "Asylvertrag", kanton: "BS", key: "BS-BeE 890.800" },
  { abk: "Asylvertrag", kanton: "BS", key: "BS-RiE 890.800" },
  { abk: "Auslagentarif für Eicharbeiten", kanton: "AR", key: "AR-956.111" },
  { abk: "Ausscheidungsvertrag", kanton: "BS", key: "BS-172.200" },
  { abk: "Ausscheidungsvertrag", kanton: "BS", key: "BS-BaB 172.200" },
  { abk: "Ausweisverordnung", kanton: "AR", key: "AR-123.1" },
  { abk: "BFSV", kanton: "BS", key: "BS-419.750" },
  { abk: "BHG", kanton: "BS", key: "BS-869.700" },
  { abk: "BHV", kanton: "BS", key: "BS-869.710" },
  { abk: "BKV", kanton: "BS", key: "BS-164.180" },
  { abk: "BLV", kanton: "AR", key: "AR-412.02" },
  { abk: "BPG", kanton: "BS", key: "BS-730.100" },
  { abk: "BPV", kanton: "BS", key: "BS-730.110" },
  { abk: "BRG", kanton: "BS", key: "BS-140.500" },
  { abk: "BRKG", kanton: "BS", key: "BS-790.100" },
  { abk: "BRV", kanton: "BS", key: "BS-140.510" },
  { abk: "BSV", kanton: "BS", key: "BS-789.710" },
  { abk: "BSchG", kanton: "BS", key: "BS-789.700" },
  { abk: "BVB-OG", kanton: "BS", key: "BS-953.100" },
  { abk: "BVO", kanton: "AR", key: "AR-142.211" },
  { abk: "BWPV", kanton: "BS", key: "BS-153.700" },
  { abk: "BZG", kanton: "BS", key: "BS-427.100" },
  { abk: "BauGebV", kanton: "BS", key: "BS-730.120" },
  { abk: "BauV", kanton: "AR", key: "AR-721.11" },
  { abk: "Baugesetz", kanton: "AR", key: "AR-721.1" },
  { abk: "Bausanierungsordnung", kanton: "BS", key: "BS-RiE 497.200" },
  { abk: "BeFiG", kanton: "AR", key: "AR-852.6" },
  { abk: "BeFiV", kanton: "AR", key: "AR-852.61" },
  { abk: "Begnadigungsgesetz", kanton: "BS", key: "BS-258.100" },
  { abk: "Behördenportalgesetz", kanton: "BS", key: "BS-153.300" },
  { abk: "Beitragsverordnung", kanton: "AR", key: "AR-721.12" },
  { abk: "Benutzungsordnung PDS", kanton: "BS", key: "BS-414.700" },
  { abk: "Berufsbildungsverordnung", kanton: "BS", key: "BS-420.210" },
  { abk: "Berufsmaturitätsverordnung", kanton: "BS", key: "BS-424.100" },
  { abk: "BestG", kanton: "BS", key: "BS-390.100" },
  { abk: "BestR", kanton: "BS", key: "BS-390.115" },
  { abk: "BestV", kanton: "BS", key: "BS-390.110" },
  { abk: "Bestattungsordnung", kanton: "BS", key: "BS-BeE 390.880" },
  { abk: "Bestattungsreglement", kanton: "BS", key: "BS-RiE 390.890" },
  { abk: "Bettelverordnung", kanton: "BS", key: "BS-257.118" },
  { abk: "Betäubungsmittelverordnung", kanton: "BS", key: "BS-340.500" },
  { abk: "BeurkG", kanton: "AR", key: "AR-211.2" },
  { abk: "BeurkGebV", kanton: "LU", key: "LU-258" },
  { abk: "BeurkGebV", kanton: "NW", key: "NW-268.12" },
  { abk: "BeurkV", kanton: "AR", key: "AR-211.211" },
  { abk: "Bevölkerungsschutzgesetz", kanton: "AR", key: "AR-511.1" },
  { abk: "Bewilligungsverordnung", kanton: "BS", key: "BS-310.120" },
  { abk: "Bistumskonkordat", kanton: "BS", key: "BS-190.500" },
  { abk: "BoSV", kanton: "BS", key: "BS-787.100" },
  { abk: "Bäderverordnung", kanton: "AR", key: "AR-811.12" },
  { abk: "BüRG", kanton: "BS", key: "BS-121.100" },
  { abk: "BüRV", kanton: "BS", key: "BS-121.110" },
  { abk: "COVID-19 Bürgschaftsverordnung", kanton: "BS", key: "BS-819.870" },
  { abk: "Chemikalienverordnung", kanton: "BS", key: "BS-340.800" },
  { abk: "Covid-19-GRB-Publikumsanlässe", kanton: "BS", key: "BS-819.878" },
  { abk: "DAGV", kanton: "BS", key: "BS-164.250" },
  { abk: "DBStV", kanton: "BS", key: "BS-660.100" },
  { abk: "DMV", kanton: "BS", key: "BS-153.310" },
  { abk: "DPV", kanton: "BS", key: "BS-497.110" },
  { abk: "Datenschutzgesetz", kanton: "AR", key: "AR-146.1" },
  { abk: "DreispitzV", kanton: "BS", key: "BS-685.320" },
  { abk: "Drohnenverordnung", kanton: "BS", key: "BS-153.275" },
  { abk: "EG AHVG/IVG", kanton: "AR", key: "AR-831.1" },
  { abk: "EG BG-KKE", kanton: "BS", key: "BS-212.850" },
  { abk: "EG BGS", kanton: "BS", key: "BS-561.100" },
  { abk: "EG FamZG", kanton: "BS", key: "BS-820.100" },
  { abk: "EG IVöB", kanton: "BS", key: "BS-914.200" },
  { abk: "EG JStPO", kanton: "BS", key: "BS-257.500" },
  { abk: "EG OHG", kanton: "BS", key: "BS-257.900" },
  { abk: "EG SVG", kanton: "AR", key: "AR-761.11" },
  { abk: "EG StPO", kanton: "BS", key: "BS-257.100" },
  { abk: "EG ZPO", kanton: "GL", key: "GL-III-C.1" },
  { abk: "EG zum BBG", kanton: "AR", key: "AR-414.11" },
  { abk: "EG zum BewG", kanton: "AR", key: "AR-213.121" },
  { abk: "EG zum FamZG", kanton: "AR", key: "AR-822.41" },
  { abk: "EG zum KUVG", kanton: "AR", key: "AR-833.11" },
  { abk: "EG zum KVG", kanton: "AR", key: "AR-833.14" },
  { abk: "EG zum ZGB", kanton: "AR", key: "AR-211.1" },
  { abk: "EG/ELG", kanton: "BS", key: "BS-832.700" },
  { abk: "EKNZ", kanton: "BS", key: "BS-300.400" },
  { abk: "EKOS", kanton: "AR", key: "AR-811.15" },
  { abk: "ERMBe", kanton: "BS", key: "BS-BeE 411.630" },
  { abk: "EV IVöB", kanton: "BS", key: "BS-914.210" },
  { abk: "EVO", kanton: "BS", key: "BS-164.150" },
  { abk: "EnG", kanton: "BS", key: "BS-772.100" },
  { abk: "EnV", kanton: "BS", key: "BS-772.110" },
  { abk: "Enteignungsgesetz", kanton: "AR", key: "AR-711.1" },
  { abk: "Enteignungsgesetz", kanton: "BS", key: "BS-740.100" },
  { abk: "FDV", kanton: "BS", key: "BS-412.400" },
  { abk: "FHG", kanton: "AR", key: "AR-612.0" },
  { abk: "FHG", kanton: "BS", key: "BS-610.100" },
  { abk: "FHV", kanton: "BS", key: "BS-428.300" },
  { abk: "FKV", kanton: "AR", key: "AR-815.13" },
  { abk: "FTG", kanton: "BS", key: "BS-569.100" },
  { abk: "FUV", kanton: "BS", key: "BS-162.410" },
  { abk: "FVKG", kanton: "BS", key: "BS-610.200" },
  { abk: "FWG", kanton: "BS", key: "BS-590.100" },
  { abk: "FWGeV", kanton: "BS", key: "BS-590.200" },
  { abk: "FWV", kanton: "BS", key: "BS-590.110" },
  { abk: "Feuerschutzgesetz", kanton: "AR", key: "AR-861.0" },
  { abk: "Feuerschutzverordnung", kanton: "AR", key: "AR-861.1" },
  { abk: "Feuerwehrkonzept", kanton: "AR", key: "AR-861.11" },
  { abk: "FhO", kanton: "BS", key: "BS-RiE 610.100" },
  { abk: "FiLaG", kanton: "BS", key: "BS-170.600" },
  { abk: "FiLaV", kanton: "BS", key: "BS-170.610" },
  { abk: "Finanzausgleichsgesetz", kanton: "AR", key: "AR-613.1" },
  { abk: "Finanzhaushaltverordnung", kanton: "BS", key: "BS-610.110" },
  { abk: "Finanzreglement", kanton: "BS", key: "BS-154.125" },
  { abk: "Finanzreglement", kanton: "BS", key: "BS-BeE 610.100" },
  { abk: "Fischereireglement", kanton: "BS", key: "BS-RiE 912.510" },
  { abk: "Fischereiverordnung", kanton: "AR", key: "AR-527.2" },
  { abk: "Fischereiverordnung", kanton: "BS", key: "BS-912.510" },
  { abk: "Fondsreglement Mehrwertabgabe", kanton: "BS", key: "BS-BeE 730.500" },
  { abk: "Fundsachenverordnung", kanton: "BS", key: "BS-214.200" },
  { abk: "FöPA", kanton: "AR", key: "AR-811.16" },
  { abk: "GBAG", kanton: "AG", key: "AG-725.100" },
  { abk: "GBGT", kanton: "LU", key: "LU-228" },
  { abk: "GGG", kanton: "TG", key: "TG-632.1" },
  { abk: "GGR", kanton: "BS", key: "BS-154.810" },
  { abk: "GGV", kanton: "AI", key: "AI-173.810" },
  { abk: "GGebR", kanton: "UR", key: "UR-2.3232" },
  { abk: "GIZA", kanton: "BS", key: "BS-119.500" },
  { abk: "GKStG", kanton: "GR", key: "GR-720.200" },
  { abk: "GKV", kanton: "BS", key: "BS-834.400" },
  { abk: "GO", kanton: "BS", key: "BS-152.100" },
  { abk: "GO KR", kanton: "AR", key: "AR-141.2" },
  { abk: "GOG", kanton: "BS", key: "BS-154.100" },
  { abk: "GOV", kanton: "AR", key: "AR-814.01.3" },
  { abk: "GRPK", kanton: "BS", key: "BS-BeE 111.200" },
  { abk: "GSK", kanton: "AR", key: "AR-955.35" },
  { abk: "GSK", kanton: "BS", key: "BS-561.111" },
  { abk: "GSV", kanton: "AR", key: "AR-621.21" },
  { abk: "GT", kanton: "SO", key: "SO-615.11" },
  { abk: "GTar", kanton: "VS", key: "VS-173.8-de" },
  { abk: "GVo", kanton: "BS", key: "BS-519.400" },
  { abk: "Gartenbad-Reglement", kanton: "BS", key: "BS-BeE 370.700" },
  { abk: "Gastgewerbegesetz", kanton: "BS", key: "BS-563.100" },
  { abk: "Gastgewerbeverordnung", kanton: "AR", key: "AR-955.111" },
  { abk: "Gasttaxenverordnung", kanton: "BS", key: "BS-650.410" },
  { abk: "GebOR", kanton: "OW", key: "OW-134.15" },
  { abk: "GebT", kanton: "AI", key: "AI-172.513" },
  { abk: "GebT", kanton: "BL", key: "BL-170.31" },
  { abk: "GebT ZGB", kanton: "GL", key: "GL-III%20B%2F7%2F1" },
  { abk: "GebT ZGB", kanton: "GL", key: "GL-III%20B_7_1" },
  { abk: "GebV", kanton: "BE", key: "BE-154.21" },
  { abk: "GebV", kanton: "BL", key: "BL-211.71" },
  { abk: "GebV", kanton: "NW", key: "NW-265.51" },
  { abk: "GebV NöRG", kanton: "BS", key: "BS-724.910" },
  { abk: "GebVGGG", kanton: "BS", key: "BS-563.170" },
  { abk: "GebVN", kanton: "BE", key: "BE-169.81" },
  { abk: "GebVZK", kanton: "BS", key: "BS-576.170" },
  { abk: "Gebäudeversicherungsgesetz", kanton: "BS", key: "BS-695.100" },
  { abk: "GebührD", kanton: "AG", key: "AG-662.110" },
  { abk: "Gebührenordnung", kanton: "AR", key: "AR-233.3" },
  { abk: "Gebührenordnung (GebO)", kanton: "SZ", key: "SZ-173.111" },
  { abk: "Gebührentarif zum EG SVG", kanton: "AR", key: "AR-761.32" },
  { abk: "Gebührenverordnung", kanton: "BS", key: "BS-453.500" },
  { abk: "Gebührenverordnung AWA", kanton: "BS", key: "BS-810.140" },
  { abk: "Gebührenverordnung PDS", kanton: "BS", key: "BS-414.710" },
  { abk: "Gebührenverordnung Sanität", kanton: "BS", key: "BS-339.220" },
  { abk: "Gemeindegesetz", kanton: "AR", key: "AR-151.11" },
  { abk: "Gemeindegesetz", kanton: "BS", key: "BS-170.100" },
  { abk: "Gerichtskostenverordnung (GKV)", kanton: "SG", key: "SG-2808" },
  { abk: "GesG", kanton: "BS", key: "BS-300.100" },
  { abk: "Gesetz über Freizeitgärten", kanton: "BS", key: "BS-911.900" },
  { abk: "Gesundheitsgesetz", kanton: "AR", key: "AR-811.1" },
  { abk: "GlV", kanton: "BS", key: "BS-140.110" },
  { abk: "GrabmV", kanton: "BS", key: "BS-390.170" },
  { abk: "Grundbuchgebührentarif", kanton: "OW", key: "OW-213.61" },
  { abk: "Grundbuchgebührentarif", kanton: "ZG", key: "ZG-215.35" },
  { abk: "Grundbuchgebührenverordnung", kanton: "SH", key: "SH-211.433" },
  { abk: "Grundwasserverordnung", kanton: "BS", key: "BS-783.410" },
  { abk: "HFSV", kanton: "BS", key: "BS-419.810" },
  { abk: "HG", kanton: "BS", key: "BS-161.100" },
  { abk: "HStG", kanton: "BE", key: "BE-215.326.2" },
  { abk: "HStG", kanton: "LU", key: "LU-645" },
  { abk: "HV", kanton: "GR", key: "GR-310.250" },
  { abk: "Handänderungssteuergesetz", kanton: "BS", key: "BS-650.100" },
  { abk: "HarmoS", kanton: "BS", key: "BS-419.600" },
  { abk: "Hausordnung", kanton: "BS", key: "BS-952.601" },
  { abk: "Hebammen-Verordnung", kanton: "AR", key: "AR-811.116" },
  { abk: "Heilmittelverordnung", kanton: "BS", key: "BS-340.100" },
  { abk: "Heimverordnung", kanton: "AR", key: "AR-811.14" },
  { abk: "Herauslösungsvereinbarung", kanton: "BS", key: "BS-954.511" },
  { abk: "HoR", kanton: "BS", key: "BS-291.400" },
  { abk: "Hochschulkonkordat", kanton: "BS", key: "BS-442.700" },
  { abk: "HonO", kanton: "SG", key: "SG-963.75" },
  { abk: "HuG", kanton: "AR", key: "AR-525.1" },
  { abk: "HuV", kanton: "AR", key: "AR-525.11" },
  { abk: "Hundegesetz", kanton: "BS", key: "BS-365.100" },
  { abk: "Hundeverordnung", kanton: "BS", key: "BS-365.110" },
  { abk: "IDG", kanton: "BS", key: "BS-153.260" },
  { abk: "IDV", kanton: "BS", key: "BS-153.270" },
  { abk: "IKV 2020", kanton: "AR", key: "AR-955.32" },
  { abk: "IKV 2020", kanton: "BS", key: "BS-561.110" },
  { abk: "IKZAV", kanton: "AR", key: "AR-615.2" },
  { abk: "IRG", kanton: "BS", key: "BS-131.100" },
  { abk: "IRV", kanton: "BS", key: "BS-670.100" },
  { abk: "ISV", kanton: "BS", key: "BS-153.320" },
  { abk: "ITGV", kanton: "BS", key: "BS-153.350" },
  { abk: "IUV", kanton: "AR", key: "AR-411.5" },
  { abk: "IUV", kanton: "BS", key: "BS-442.300" },
  { abk: "IVHSM", kanton: "BS", key: "BS-333.100" },
  { abk: "IVSE", kanton: "AR", key: "AR-852.5" },
  { abk: "IVSE", kanton: "BS", key: "BS-869.100" },
  { abk: "IVTH", kanton: "BS", key: "BS-910.500" },
  { abk: "IVöB", kanton: "BS", key: "BS-914.600" },
  { abk: "IWB-Gesetz", kanton: "BS", key: "BS-772.300" },
  { abk: "ImmoV", kanton: "BS", key: "BS-442.410" },
  { abk: "Informatikreglement", kanton: "BS", key: "BS-154.128" },
  { abk: "Informationsgesetz", kanton: "AR", key: "AR-133.1" },
  { abk: "InkaV", kanton: "BS", key: "BS-610.150" },
  { abk: "IntV", kanton: "BS", key: "BS-122.510" },
  { abk: "Integrationsgesetz", kanton: "BS", key: "BS-122.500" },
  { abk: "JG", kanton: "SH", key: "SH-173.200" },
  { abk: "JR", kanton: "FR", key: "FR-130.11-de" },
  { abk: "JStVG", kanton: "BS", key: "BS-258.400" },
  { abk: "JVG", kanton: "AR", key: "AR-341.1" },
  { abk: "JVG", kanton: "BS", key: "BS-258.200" },
  { abk: "JVV", kanton: "BS", key: "BS-258.210" },
  { abk: "Jagdgesetz", kanton: "AR", key: "AR-526.2" },
  { abk: "Jagdverordnung", kanton: "AR", key: "AR-526.21" },
  { abk: "JusKV", kanton: "LU", key: "LU-265" },
  { abk: "Justizgesetz", kanton: "AR", key: "AR-145.31" },
  { abk: "KAVI", kanton: "AR", key: "AR-212.331" },
  { abk: "KBBV", kanton: "BS", key: "BS-212.470" },
  { abk: "KBV", kanton: "BS", key: "BS-832.720" },
  { abk: "KESG", kanton: "BS", key: "BS-212.400" },
  { abk: "KFWV", kanton: "BS", key: "BS-730.210" },
  { abk: "KGS", kanton: "AR", key: "AR-955.31" },
  { abk: "KGV", kanton: "AR", key: "AR-233.21" },
  { abk: "KGV", kanton: "BS", key: "BS-576.180" },
  { abk: "KGeoIG", kanton: "BS", key: "BS-214.300" },
  { abk: "KGeoIV", kanton: "BS", key: "BS-214.305" },
  { abk: "KGlG", kanton: "BS", key: "BS-140.100" },
  { abk: "KJG", kanton: "BS", key: "BS-415.100" },
  { abk: "KJHVO", kanton: "BS", key: "BS-212.250" },
  { abk: "KJKV", kanton: "BS", key: "BS-415.150" },
  { abk: "KKO VO", kanton: "BS", key: "BS-153.200" },
  { abk: "KOBV", kanton: "BS", key: "BS-257.115" },
  { abk: "KR AsylVo", kanton: "AR", key: "AR-122.24" },
  { abk: "KRG", kanton: "AR", key: "AR-141.1" },
  { abk: "KTV", kanton: "BS", key: "BS-815.110" },
  { abk: "KVO", kanton: "BS", key: "BS-834.410" },
  { abk: "Kaminfegertarif", kanton: "AR", key: "AR-861.4" },
  { abk: "Kantonales Waldgesetz", kanton: "AR", key: "AR-931.1" },
  { abk: "KibeG", kanton: "AR", key: "AR-415.31" },
  { abk: "KibeV", kanton: "AR", key: "AR-415.311" },
  { abk: "Kinderspitalvertrag", kanton: "BS", key: "BS-331.300" },
  { abk: "Kirchengesetz", kanton: "BS", key: "BS-190.100" },
  { abk: "Kleinschifffahrtsverordnung", kanton: "BS", key: "BS-955.100" },
  { abk: "KoGesV", kanton: "BS", key: "BS-510.170" },
  { abk: "KoV OG", kanton: "ZG", key: "ZG-161.7" },
  { abk: "Korporationsordnung", kanton: "BS", key: "BS-BaB 155.400" },
  { abk: "Krebsregistervereinbarung", kanton: "BS", key: "BS-300.315" },
  { abk: "Kulturfördergesetz", kanton: "BS", key: "BS-494.300" },
  { abk: "Kulturförderungsgesetz", kanton: "AR", key: "AR-420.1" },
  { abk: "Kulturförderungsverordnung", kanton: "AR", key: "AR-420.11" },
  { abk: "Kulturvertrag", kanton: "BS", key: "BS-494.100" },
  { abk: "KÖREBKV", kanton: "BS", key: "BS-214.307" },
  { abk: "LDM", kanton: "VS", key: "VS-643.1" },
  { abk: "LDMG", kanton: "FR", key: "FR-635.1.1" },
  { abk: "LG", kanton: "BS", key: "BS-164.100" },
  { abk: "LHV", kanton: "BS", key: "BS-781.200" },
  { abk: "LKV", kanton: "AR", key: "AR-815.11" },
  { abk: "LNV", kanton: "BS", key: "BS-164.430" },
  { abk: "LQBV", kanton: "AR", key: "AR-920.17" },
  { abk: "LSV BS", kanton: "BS", key: "BS-782.100" },
  { abk: "LTar", kanton: "VS", key: "VS-173.8-fr" },
  { abk: "LoFV", kanton: "AR", key: "AR-955.321" },
  { abk: "Lohnordnung", kanton: "BS", key: "BS-BaB 164.100" },
  { abk: "Lohnordnung", kanton: "BS", key: "BS-RiE 164.100" },
  { abk: "Lohnreglement", kanton: "BS", key: "BS-RiE 164.110" },
  { abk: "MAR", kanton: "BS", key: "BS-419.910" },
  { abk: "MBVO", kanton: "BS", key: "BS-890.510" },
  { abk: "MHG", kanton: "AR", key: "AR-413.1" },
  { abk: "MHV", kanton: "AR", key: "AR-413.11" },
  { abk: "MPV", kanton: "BS", key: "BS-413.820" },
  { abk: "MR", kanton: "BS", key: "BS-861.625" },
  { abk: "Massnahmenverordnung", kanton: "BS", key: "BS-781.220" },
  { abk: "MiLoG", kanton: "BS", key: "BS-812.200" },
  { abk: "MiLoV", kanton: "BS", key: "BS-812.210" },
  { abk: "Mietbeitragsgesetz MBG", kanton: "BS", key: "BS-890.500" },
  { abk: "Mitwirkungsreglement", kanton: "BS", key: "BS-BeE 153.500" },
  { abk: "Mobilitätsfondsverordnung", kanton: "BS", key: "BS-780.300" },
  { abk: "Museumsgesetz", kanton: "BS", key: "BS-451.100" },
  { abk: "Museumsverordnung", kanton: "BS", key: "BS-451.110" },
  { abk: "Münchenstein", kanton: "BS", key: "BS-952.801" },
  { abk: "NAG", kanton: "BS", key: "BS-122.200" },
  { abk: "NAV", kanton: "BS", key: "BS-122.210" },
  { abk: "NAV Haushalt BS", kanton: "BS", key: "BS-215.700" },
  { abk: "NAV LW", kanton: "BS", key: "BS-215.600" },
  { abk: "Naturbadreglement", kanton: "BS", key: "BS-RiE 370.700" },
  { abk: "NoVo", kanton: "BS", key: "BS-292.110" },
  { abk: "NotGebV", kanton: "BL", key: "BL-217.13" },
  { abk: "NotGebV", kanton: "GR", key: "GR-210.370" },
  { abk: "NöRG", kanton: "BS", key: "BS-724.100" },
  { abk: "NöRV", kanton: "BS", key: "BS-724.110" },
  { abk: "OBK-Reglement", kanton: "BS", key: "BS-RiE 730.350" },
  { abk: "OG", kanton: "BS", key: "BS-153.100" },
  { abk: "OPR", kanton: "BS", key: "BS-RiE 132.100" },
  { abk: "OcRF", kanton: "VS", key: "VS-211.611" },
  { abk: "OgR", kanton: "BS", key: "BS-RiE 153.100" },
  { abk: "OrG", kanton: "AR", key: "AR-142.12" },
  { abk: "OrV", kanton: "AR", key: "AR-142.121" },
  { abk: "Ordnung K-Netz Riehen", kanton: "BS", key: "BS-RiE 970.110" },
  { abk: "Organisationsreglement", kanton: "BS", key: "BS-BeE 153.210" },
  { abk: "PAFV", kanton: "BS", key: "BS-310.125" },
  { abk: "PBV", kanton: "BS", key: "BS-563.500" },
  { abk: "PFG", kanton: "AR", key: "AR-833.15" },
  { abk: "PFV", kanton: "AR", key: "AR-833.151" },
  { abk: "PFVO", kanton: "BS", key: "BS-212.260" },
  { abk: "PG", kanton: "AR", key: "AR-142.21" },
  { abk: "PGV", kanton: "AR", key: "AR-142.212" },
  { abk: "PKG", kanton: "AR", key: "AR-142.22" },
  { abk: "PKG", kanton: "BS", key: "BS-166.100" },
  { abk: "PKV", kanton: "BE", key: "BE-168.811" },
  { abk: "PKoG", kanton: "NW", key: "NW-261.2" },
  { abk: "PPV", kanton: "BS", key: "BS-730.310" },
  { abk: "PRBV", kanton: "BS", key: "BS-952.560" },
  { abk: "Parkgaragenverordnung", kanton: "BS", key: "BS-952.600" },
  { abk: "Parkplatz-Reglement", kanton: "BS", key: "BS-163.900" },
  { abk: "Passerelleverordnung", kanton: "BS", key: "BS-424.500" },
  { abk: "Perimeterverordnung", kanton: "AR", key: "AR-742.1" },
  { abk: "Personalausschussverordnung", kanton: "BS", key: "BS-169.300" },
  { abk: "Personalgesetz", kanton: "BS", key: "BS-162.100" },
  { abk: "Personalordnung", kanton: "BS", key: "BS-BeE 162.100" },
  { abk: "Personalordnung", kanton: "BS", key: "BS-RiE 162.100" },
  { abk: "Personalreglement", kanton: "BS", key: "BS-RiE 162.110" },
  { abk: "Personalreglement der Gerichte", kanton: "BS", key: "BS-154.112" },
  { abk: "Pflanzenschutzverordnung", kanton: "AR", key: "AR-920.11" },
  { abk: "Pflegebeitragsverordnung", kanton: "BS", key: "BS-329.110" },
  { abk: "Plakatverordnung", kanton: "BS", key: "BS-569.500" },
  { abk: "PolG", kanton: "BS", key: "BS-510.100" },
  { abk: "PolV", kanton: "AR", key: "AR-521.11" },
  { abk: "PolV", kanton: "BS", key: "BS-510.110" },
  { abk: "Polizeigesetz", kanton: "AR", key: "AR-521.1" },
  { abk: "Psychiatriegesetz", kanton: "BS", key: "BS-323.100" },
  { abk: "PublV", kanton: "BS", key: "BS-151.210" },
  { abk: "Publikationsgesetz", kanton: "BS", key: "BS-151.200" },
  { abk: "RAKA", kanton: "BS", key: "BS-419.902" },
  { abk: "REEMu", kanton: "BS", key: "BS-RiE 411.630" },
  { abk: "REIS", kanton: "AR", key: "AR-142.211.1" },
  { abk: "RJ", kanton: "FR", key: "FR-130.11-fr" },
  { abk: "RLG", kanton: "BS", key: "BS-811.100" },
  { abk: "RPR", kanton: "BS", key: "BS-RiE 132.110" },
  { abk: "RR AsylVo", kanton: "AR", key: "AR-122.241" },
  { abk: "RSA 2009", kanton: "BS", key: "BS-419.700" },
  { abk: "RebV", kanton: "AR", key: "AR-920.161" },
  { abk: "Registergesetz", kanton: "AR", key: "AR-122.1" },
  { abk: "Reglement Bildende Kunst", kanton: "BS", key: "BS-RiE 494.300" },
  { abk: "Reglement GFS", kanton: "BS", key: "BS-RiE 153.170" },
  { abk: "Reglement Mehrweggeschirr", kanton: "BS", key: "BS-RiE 786.180" },
  { abk: "Reglement zur Lohnordnung", kanton: "BS", key: "BS-BaB 164.110" },
  { abk: "Rheinhafen-Vertrag", kanton: "BS", key: "BS-955.400" },
  { abk: "Richtlinien Mietzinsgestaltung", kanton: "BS", key: "BS-861.626" },
  { abk: "Römervertrag", kanton: "BS", key: "BS-497.800" },
  { abk: "SBV", kanton: "BS", key: "BS-815.150" },
  { abk: "SFAV", kanton: "AR", key: "AR-766.1" },
  { abk: "SHG", kanton: "AR", key: "AR-851.1" },
  { abk: "SHV", kanton: "AR", key: "AR-851.11" },
  { abk: "SLV", kanton: "AR", key: "AR-412.03" },
  { abk: "SLV", kanton: "BS", key: "BS-410.700" },
  { abk: "SMUV", kanton: "BS", key: "BS-162.420" },
  { abk: "SPSSV", kanton: "BS", key: "BS-412.750" },
  { abk: "SVARG", kanton: "AR", key: "AR-812.11" },
  { abk: "SVGG", kanton: "BS", key: "BS-154.200" },
  { abk: "Schadenwehrverordnung", kanton: "AR", key: "AR-814.01.2" },
  { abk: "Schlichtungsstellengesetz", kanton: "BS", key: "BS-215.400" },
  { abk: "Schulgeldverordnung", kanton: "BS", key: "BS-419.100" },
  { abk: "Schulgesetz", kanton: "BS", key: "BS-410.100" },
  { abk: "Schulordnung", kanton: "BS", key: "BS-RiE 411.600" },
  { abk: "Schulreglement", kanton: "BS", key: "BS-RiE 411.610" },
  { abk: "Schulvereinbarung", kanton: "BS", key: "BS-412.100" },
  { abk: "Schulvereinbarung", kanton: "BS", key: "BS-BeE 412.100" },
  { abk: "Schulvereinbarung", kanton: "BS", key: "BS-RiE 412.100" },
  { abk: "Schulvertrag", kanton: "BS", key: "BS-BeE 411.500" },
  { abk: "Schulvertrag", kanton: "BS", key: "BS-RiE 411.500" },
  { abk: "Smog-Verordnung", kanton: "BS", key: "BS-781.500" },
  { abk: "SoHaG", kanton: "BS", key: "BS-890.700" },
  { abk: "SoHaV", kanton: "BS", key: "BS-890.710" },
  { abk: "Sozialhilfegesetz", kanton: "BS", key: "BS-890.100" },
  { abk: "Sozialhilfeordnung", kanton: "BS", key: "BS-BeE 890.510" },
  { abk: "Sozialhilfeordnung", kanton: "BS", key: "BS-RiE 890.100" },
  { abk: "Sozialhilfereglement", kanton: "BS", key: "BS-RiE 890.110" },
  { abk: "Spesenverordnung", kanton: "BS", key: "BS-164.420" },
  { abk: "Sportfondsverordnung", kanton: "AR", key: "AR-612.3" },
  { abk: "Sportgesetz", kanton: "BS", key: "BS-371.100" },
  { abk: "Sportplatzreglement", kanton: "BS", key: "BS-RiE 681.700" },
  { abk: "StBG", kanton: "BS", key: "BS-610.500" },
  { abk: "StG", kanton: "AI", key: "AI-640.000" },
  { abk: "StG", kanton: "BS", key: "BS-640.100" },
  { abk: "StG", kanton: "NW", key: "NW-521.1" },
  { abk: "StG", kanton: "OW", key: "OW-641.4" },
  { abk: "StG", kanton: "SG", key: "SG-811.1" },
  { abk: "StG", kanton: "TG", key: "TG-640.1" },
  { abk: "StV", kanton: "BS", key: "BS-640.110" },
  { abk: "StVO", kanton: "BS", key: "BS-952.200" },
  { abk: "StaföG", kanton: "BS", key: "BS-910.200" },
  { abk: "StaföV", kanton: "BS", key: "BS-910.210" },
  { abk: "StatG", kanton: "BS", key: "BS-453.200" },
  { abk: "Statistikverordnung", kanton: "BS", key: "BS-453.210" },
  { abk: "Stellvertretungsverordnung", kanton: "BS", key: "BS-164.440" },
  { abk: "Steuergesetz", kanton: "AR", key: "AR-621.11" },
  { abk: "Steuergesetz", kanton: "BL", key: "BL-331" },
  { abk: "Steuergesetz", kanton: "SO", key: "SO-614.11" },
  { abk: "Steuerreglement", kanton: "BS", key: "BS-RiE 640.110" },
  { abk: "Steuerverordnung", kanton: "AR", key: "AR-621.111" },
  { abk: "Stipendiengesetz", kanton: "AR", key: "AR-415.21" },
  { abk: "Stipendienverordnung", kanton: "AR", key: "AR-415.211" },
  { abk: "StrG", kanton: "AR", key: "AR-731.11" },
  { abk: "StrV", kanton: "AR", key: "AR-731.111" },
  { abk: "Swisslos-Fonds-Verordnung", kanton: "BS", key: "BS-561.120" },
  { abk: "Swisslos-Sportfonds-Verordnung", kanton: "BS", key: "BS-561.121" },
  { abk: "TBG", kanton: "BS", key: "BS-815.100" },
  { abk: "TBV", kanton: "BS", key: "BS-815.120" },
  { abk: "TFV", kanton: "BS", key: "BS-412.600" },
  { abk: "TG", kanton: "AR", key: "AR-955.21" },
  { abk: "TGV", kanton: "AR", key: "AR-925.32" },
  { abk: "TPV", kanton: "BS", key: "BS-562.530" },
  { abk: "TV", kanton: "AR", key: "AR-955.213" },
  { abk: "TZV", kanton: "AR", key: "AR-920.14" },
  { abk: "Tarif KESR", kanton: "AR", key: "AR-212.43" },
  { abk: "Taxi-ARV", kanton: "BS", key: "BS-812.350" },
  { abk: "Taxigesetz", kanton: "BS", key: "BS-563.200" },
  { abk: "Taxiprüfungsreglement", kanton: "BS", key: "BS-563.250" },
  { abk: "Taxitarifverordnung", kanton: "BS", key: "BS-563.280" },
  { abk: "Taxiverordnung", kanton: "BS", key: "BS-563.210" },
  { abk: "Tierschutzverordnung", kanton: "AR", key: "AR-422.2" },
  { abk: "Tierschutzverordnung", kanton: "BS", key: "BS-365.500" },
  { abk: "UGsG", kanton: "AR", key: "AR-814.0" },
  { abk: "UGsV", kanton: "AR", key: "AR-814.01" },
  { abk: "USG BS", kanton: "BS", key: "BS-780.100" },
  { abk: "UVPV BS", kanton: "BS", key: "BS-780.200" },
  { abk: "UZBG", kanton: "BS", key: "BS-300.600" },
  { abk: "Universitätsgutsgesetz", kanton: "BS", key: "BS-440.400" },
  { abk: "Universitätsstatut", kanton: "BS", key: "BS-440.110" },
  { abk: "V GöV", kanton: "AR", key: "AR-760.11" },
  { abk: "V zum FamZG", kanton: "AR", key: "AR-822.411" },
  { abk: "V zum KVG", kanton: "AR", key: "AR-833.141" },
  { abk: "VEAV", kanton: "AR", key: "AR-925.321" },
  { abk: "VEEG", kanton: "BS", key: "BS-772.180" },
  { abk: "VELG", kanton: "BS", key: "BS-832.710" },
  { abk: "VGG", kanton: "TG", key: "TG-638.1" },
  { abk: "VGWR BS", kanton: "BS", key: "BS-453.100" },
  { abk: "VGZ", kanton: "GR", key: "GR-320.210" },
  { abk: "VIZA", kanton: "BS", key: "BS-119.510" },
  { abk: "VKD", kanton: "BE", key: "BE-161.12" },
  { abk: "VKGS", kanton: "AR", key: "AR-955.311" },
  { abk: "VNBV", kanton: "AR", key: "AR-920.18" },
  { abk: "VO EG BGS", kanton: "BS", key: "BS-561.105" },
  { abk: "VO HAKES", kanton: "BS", key: "BS-212.860" },
  { abk: "VOAV", kanton: "BS", key: "BS-214.320" },
  { abk: "VOGB", kanton: "BS", key: "BS-214.310" },
  { abk: "VPG", kanton: "BS", key: "BS-162.110" },
  { abk: "VPTI", kanton: "AR", key: "AR-522.3" },
  { abk: "VRPG", kanton: "AR", key: "AR-143.1" },
  { abk: "VRPG", kanton: "BS", key: "BS-270.100" },
  { abk: "VSG", kanton: "AR", key: "AR-412.00" },
  { abk: "VSMS BS", kanton: "BS", key: "BS-510.150" },
  { abk: "VSV", kanton: "AR", key: "AR-412.01" },
  { abk: "VStA", kanton: "AR", key: "AR-212.01" },
  { abk: "VVAusbBG", kanton: "BS", key: "BS-491.110" },
  { abk: "VZH", kanton: "BS", key: "BS-310.420" },
  { abk: "VZS", kanton: "BS", key: "BS-576.150" },
  { abk: "VeloPPV", kanton: "BS", key: "BS-730.320" },
  { abk: "Vereinbarung Sanitätsdienst", kanton: "BS", key: "BS-339.240" },
  { abk: "Vernehmlassungsverordnung", kanton: "BS", key: "BS-133.300" },
  { abk: "Verordnung AGS LzB", kanton: "BS", key: "BS-421.760" },
  { abk: "Verordnung Kulturvermittlung", kanton: "BS", key: "BS-494.330" },
  { abk: "Verordnung Ladeinfrastruktur", kanton: "BS", key: "BS-780.360" },
  { abk: "Verordnung zum Kirchengesetz", kanton: "BS", key: "BS-190.110" },
  { abk: "Verordnung zum Registergesetz", kanton: "AR", key: "AR-122.11" },
  { abk: "Vertrag Gesundheitsberufe", kanton: "BS", key: "BS-427.150" },
  { abk: "Verwaltungsgebührenreglement", kanton: "BS", key: "BS-BeE 153.840" },
  { abk: "Verwaltungsgebührentarif", kanton: "ZG", key: "ZG-641.1" },
  { abk: "Verwaltungsordnung", kanton: "BS", key: "BS-BaB 155.700" },
  { abk: "Veterinärvereinbarung", kanton: "BS", key: "BS-365.300" },
  { abk: "ViCLAS-Konkordat", kanton: "BS", key: "BS-257.810" },
  { abk: "ViCLAS-Verordnung", kanton: "BS", key: "BS-257.815" },
  { abk: "VoAGOV", kanton: "BS", key: "BS-153.340" },
  { abk: "VoKESG", kanton: "BS", key: "BS-212.410" },
  { abk: "Vorstadtordnung", kanton: "BS", key: "BS-BaB 155.200" },
  { abk: "VuV", kanton: "BS", key: "BS-780.350" },
  { abk: "VvEpG", kanton: "BS", key: "BS-321.200" },
  { abk: "VvP", kanton: "BS", key: "BS-162.320" },
  { abk: "VvTabPG", kanton: "BS", key: "BS-300.150" },
  { abk: "WBauG", kanton: "AR", key: "AR-741.1" },
  { abk: "WBauV", kanton: "AR", key: "AR-741.11" },
  { abk: "WFV", kanton: "BS", key: "BS-310.140" },
  { abk: "WJG", kanton: "BS", key: "BS-912.200" },
  { abk: "WJV", kanton: "BS", key: "BS-912.210" },
  { abk: "WRFG", kanton: "BS", key: "BS-861.500" },
  { abk: "WRFV", kanton: "BS", key: "BS-861.520" },
  { abk: "WRSchV", kanton: "BS", key: "BS-861.540" },
  { abk: "WSG", kanton: "BS", key: "BS-861.600" },
  { abk: "WaG BS", kanton: "BS", key: "BS-911.600" },
  { abk: "WaV BS", kanton: "BS", key: "BS-911.610" },
  { abk: "Waffenverordnung", kanton: "BS", key: "BS-568.200" },
  { abk: "Wahlgesetz", kanton: "BS", key: "BS-132.100" },
  { abk: "Wahlverordnung", kanton: "BS", key: "BS-132.110" },
  { abk: "Wassernutzungsgesetz", kanton: "BS", key: "BS-771.500" },
  { abk: "Wassernutzungsverordnung", kanton: "BS", key: "BS-771.510" },
  { abk: "Whistleblowing-Verordnung", kanton: "BS", key: "BS-162.600" },
  { abk: "ZKG", kanton: "BS", key: "BS-576.100" },
  { abk: "Zahnpflegeordnung", kanton: "BS", key: "BS-BeE 328.600" },
  { abk: "Zahnpflegereglement", kanton: "BS", key: "BS-RiE 328.610" },
  { abk: "Zahnpflegeverordnung", kanton: "BS", key: "BS-328.210" },
  { abk: "Zahpflegeordnung", kanton: "BS", key: "BS-RiE 328.600" },
  { abk: "Zivilschutzgesetz", kanton: "AR", key: "AR-511.2" },
  { abk: "Zonenordnung Riehen", kanton: "BS", key: "BS-RiE 730.130" },
  { abk: "Zufahrtsverordnung", kanton: "BS", key: "BS-952.300" },
  { abk: "Zulagenverordnung", kanton: "BS", key: "BS-164.410" },
  { abk: "Zunftordnung", kanton: "BS", key: "BS-BaB 155.100" },
  { abk: "Zusammenarbeits-Vereinbarung", kanton: "BS", key: "BS-956.400" },
  { abk: "Zusatzabkommen V", kanton: "BS", key: "BS-172.400" },
  { abk: "Zusatzabkommen V", kanton: "BS", key: "BS-BaB 172.400" },
  { abk: "eGovG", kanton: "AR", key: "AR-142.3" },
  { abk: "kEnG", kanton: "AR", key: "AR-750.1" },
  { abk: "kEnV", kanton: "AR", key: "AR-750.11" },
  { abk: "kGBV", kanton: "AR", key: "AR-213.310" },
  { abk: "kGeoIG", kanton: "AR", key: "AR-723.1" },
  { abk: "kGeoIV", kanton: "AR", key: "AR-723.101" },
  { abk: "kOBV", kanton: "AR", key: "AR-323.1" },
  { abk: "kRLV", kanton: "AR", key: "AR-765.1" },
  { abk: "kVAV", kanton: "AR", key: "AR-723.105" },
  { abk: "kWeinV", kanton: "AR", key: "AR-920.16" },
  { abk: "kant. BBV", kanton: "AR", key: "AR-414.111" },
  { abk: "kantonale Waldverordnung", kanton: "AR", key: "AR-931.11" },
  { abk: "kÖREBKV", kanton: "AR", key: "AR-723.104" },
  { abk: "ÖSpG", kanton: "BS", key: "BS-331.100" },
  { abk: "ÖV-Verordnung", kanton: "BS", key: "BS-951.110" },
  { abk: "ÜStG", kanton: "BS", key: "BS-253.100" },
  { abk: "Übertrittsverordnung", kanton: "BS", key: "BS-411.520" },
];
