// AUTO-GENERIERT von scripts/normtext/fedlex-abk-generieren.ts — NICHT von Hand editieren.
//
// Amtliche Kurzbezeichnungen (`jolux:titleShort`) je SR-Nummer und Amtssprache,
// verbatim aus den Fedlex-Metadaten (§7: Quelle + Abruf-Stand, kein Hand-Erraten).
// Quelle : https://fedlex.data.admin.ch/sparqlendpoint (SPARQL, jolux-Ontologie)
// Stand  : 2026-07-28 (Abrufdatum; Applicability-Fenster: aufgehobene Erlasse mit
//          dateNoLongerInForce <= Abrufdatum sind ausgeschlossen)
// Live   : https://www.fedlex.admin.ch/de/cc/internal-law/<SR-Zweig> (geltende Fassung)
// Regen  : npm run gen:fedlex-abk   ·   Drift-Tor: npm run check:fedlex-abk-netz
//
// Reine Daten (§3): die Zuordnung SR → Register-key macht scripts/normtext/
// entscheide-mapping.ts. `null` = Fedlex führt für diese Sprache kein Kürzel.

export interface FedlexAbk {
  /** SR-Nummer (Systematische Rechtssammlung), z.B. "173.110". */
  sr: string;
  /** Amtliches deutsches Kürzel, verbatim («BVV 2», «GebV SchKG»). */
  de: string | null;
  /** Amtliches französisches Kürzel, verbatim («LTF», «Cst.»). */
  fr: string | null;
  /** Amtliches italienisches Kürzel, verbatim («LTF», «Cost.»). */
  it: string | null;
}

export const FEDLEX_ABK_STAND = "2026-07-28";

export const FEDLEX_ABK: readonly FedlexAbk[] = [
  { sr: "0.101", de: "EMRK", fr: "CEDH", it: "CEDU" },
  { sr: "0.142.112.681", de: "FZA", fr: "ALCP", it: "ALC" },
  { sr: "0.142.30", de: "FK", fr: null, it: null },
  { sr: "0.211.231.011", de: "HKsÜ", fr: "CLaH 96", it: null },
  { sr: "0.275.12", de: "LugÜ", fr: "CL", it: "CLug" },
  { sr: "0.741.611", de: "CMR", fr: "CMR", it: "CMR" },
  { sr: "101", de: "BV", fr: "Cst.", it: "Cost." },
  { sr: "141.0", de: "BüG", fr: "LN", it: "LCit" },
  { sr: "141.01", de: "BüV", fr: "OLN", it: "OCit" },
  { sr: "142.20", de: "AIG", fr: "LEI", it: "LStrI" },
  { sr: "142.201", de: "VZAE", fr: "OASA", it: "OASA" },
  { sr: "142.204", de: "VEV", fr: "OEV", it: "OEV" },
  { sr: "142.205", de: "VIntA", fr: "OIE", it: "OIntS" },
  { sr: "142.31", de: "AsylG", fr: "LAsi", it: "LAsi" },
  { sr: "142.311", de: "AsylV 1", fr: "OA 1", it: "OAsi 1" },
  { sr: "142.312", de: "AsylV 2", fr: "OA 2", it: "OAsi 2" },
  { sr: "142.314", de: "AsylV 3", fr: "OA 3", it: "OAsi 3" },
  { sr: "143.5", de: "RDV", fr: "ODV", it: "ODV" },
  { sr: "151.1", de: "GlG", fr: "LEg", it: "LPar" },
  { sr: "152.3", de: "BGÖ", fr: "LTrans", it: "LTras" },
  { sr: "161.1", de: "BPR", fr: "LDP", it: "LDP" },
  { sr: "170.32", de: "VG", fr: "LRCF", it: "LResp" },
  { sr: "170.512", de: "PublG", fr: "LPubl", it: "LPubb" },
  { sr: "171.10", de: "ParlG", fr: "LParl", it: "LParl" },
  { sr: "172.010", de: "RVOG", fr: "LOGA", it: "LOGA" },
  { sr: "172.010.1", de: "RVOV", fr: "OLOGA", it: "OLOGA" },
  { sr: "172.021", de: "VwVG", fr: "PA", it: "PA" },
  { sr: "172.056.1", de: "BöB", fr: "LMP", it: "LAPub" },
  { sr: "172.056.11", de: "VöB", fr: "OMP", it: "OAPub" },
  { sr: "172.220.1", de: "BPG", fr: "LPers", it: "LPers" },
  { sr: "172.220.111.3", de: "BPV", fr: "OPers", it: "OPers" },
  { sr: "173.110", de: "BGG", fr: "LTF", it: "LTF" },
  { sr: "173.110.131", de: "BGerR", fr: "RTF", it: "RTF" },
  { sr: "173.32", de: "VGG", fr: "LTAF", it: "LTAF" },
  { sr: "173.320.1", de: "VGR", fr: "RTAF", it: "RTAF" },
  { sr: "173.320.2", de: "VGKE", fr: "FITAF", it: "TS-TAF" },
  { sr: "173.71", de: "StBOG", fr: "LOAP", it: "LOAP" },
  { sr: "210", de: "ZGB", fr: "CC", it: "CC" },
  { sr: "211.112.2", de: "ZStV", fr: "OEC", it: "OSC" },
  { sr: "211.221.36", de: "AdoV", fr: "OAdo", it: "OAdoz" },
  { sr: "211.222.338", de: "PAVO", fr: "OPE", it: "OAMin" },
  { sr: "211.231", de: "PartG", fr: "LPart", it: "LUD" },
  { sr: "211.412.11", de: "BGBB", fr: "LDFR", it: "LDFR" },
  { sr: "211.412.41", de: "BewG", fr: "LFAIE", it: "LAFE" },
  { sr: "211.412.411", de: "BewV", fr: "OAIE", it: "OAFE" },
  { sr: "211.432.1", de: "GBV", fr: "ORF", it: "ORF" },
  { sr: "211.432.11", de: "TGBV", fr: "OTRF", it: "OTRF" },
  { sr: "220", de: "OR", fr: "CO", it: "CO" },
  { sr: "221.112.944", de: "PrHG", fr: "LRFP", it: "LRDP" },
  { sr: "221.213.11", de: "VMWG", fr: "OBLF", it: "OLAL" },
  { sr: "221.214.1", de: "KKG", fr: "LCC", it: "LCC" },
  { sr: "221.214.11", de: "VKKG", fr: "OLCC", it: "OLCC" },
  { sr: "221.229.1", de: "VVG", fr: "LCA", it: "LCA" },
  { sr: "221.301", de: "FusG", fr: "LFus", it: "LFus" },
  { sr: "221.411", de: "HRegV", fr: "ORC", it: "ORC" },
  { sr: "221.411.1", de: "GebV-HReg", fr: "OEmol-RC", it: "OEmol-RC" },
  { sr: "231.1", de: "URG", fr: "LDA", it: "LDA" },
  { sr: "231.11", de: "URV", fr: "ODAu", it: "ODAu" },
  { sr: "232.11", de: "MSchG", fr: "LPM", it: "LPM" },
  { sr: "232.111", de: "MSchV", fr: "OPM", it: "OPM" },
  { sr: "232.12", de: "DesG", fr: "LDes", it: "LDes" },
  { sr: "232.121", de: "DesV", fr: "ODes", it: "ODes" },
  { sr: "232.14", de: "PatG", fr: "LBI", it: "LBI" },
  { sr: "232.141", de: "PatV", fr: "OBI", it: "OBI" },
  { sr: "235.1", de: "DSG", fr: "LPD", it: "LPD" },
  { sr: "235.11", de: "DSV", fr: "OPDo", it: "OPDa" },
  { sr: "241", de: "UWG", fr: "LCD", it: "LCSl" },
  { sr: "251", de: "KG", fr: "LCart", it: "LCart" },
  { sr: "272", de: "ZPO", fr: "CPC", it: "CPC" },
  { sr: "281.1", de: "SchKG", fr: "LP", it: "LEF" },
  { sr: "281.31", de: "VFRR", fr: "Oform", it: "Rform" },
  { sr: "281.32", de: "KOV", fr: "OAOF", it: "RUF" },
  { sr: "281.35", de: "GebV SchKG", fr: "OELP", it: "OTLEF" },
  { sr: "281.42", de: "VZG", fr: "ORFI", it: "RFF" },
  { sr: "291", de: "IPRG", fr: "LDIP", it: "LDIP" },
  { sr: "311.0", de: "StGB", fr: "CP", it: "CP" },
  { sr: "311.1", de: "JStG", fr: "DPMin", it: "DPMin" },
  { sr: "312.0", de: "StPO", fr: "CPP", it: "CPP" },
  { sr: "312.1", de: "JStPO", fr: "PPMin", it: "PPMin" },
  { sr: "312.5", de: "OHG", fr: "LAVI", it: "LAV" },
  { sr: "313.0", de: "VStrR", fr: "DPA", it: "DPA" },
  { sr: "321.0", de: "MStG", fr: "CPM", it: "CPM" },
  { sr: "322.1", de: "MStP", fr: "PPM", it: "PPM" },
  { sr: "351.1", de: "IRSG", fr: "EIMP", it: "AIMP" },
  { sr: "364.3", de: "ZAV", fr: "OLUsC", it: "OCoe" },
  { sr: "412.10", de: "BBG", fr: "LFPr", it: "LFPr" },
  { sr: "412.101", de: "BBV", fr: "OFPr", it: "OFPr" },
  { sr: "412.103.1", de: "BMV", fr: "OMPr", it: "OMPr" },
  { sr: "451", de: "NHG", fr: "LPN", it: "LPN" },
  { sr: "451.1", de: "NHV", fr: "OPN", it: "OPN" },
  { sr: "510.10", de: "MG", fr: "LAAM", it: "LM" },
  { sr: "641.10", de: "StG", fr: "LT", it: "LTB" },
  { sr: "641.20", de: "MWSTG", fr: "LTVA", it: "LIVA" },
  { sr: "641.201", de: "MWSTV", fr: "OTVA", it: "OIVA" },
  { sr: "642.11", de: "DBG", fr: "LIFD", it: "LIFD" },
  { sr: "642.118.2", de: "QStV", fr: "OIS", it: "OIFo" },
  { sr: "642.14", de: "StHG", fr: "LHID", it: "LAID" },
  { sr: "642.21", de: "VStG", fr: "LIA", it: "LIP" },
  { sr: "642.211", de: "VStV", fr: "OIA", it: "OIPrev" },
  { sr: "700", de: "RPG", fr: "LAT", it: "LPT" },
  { sr: "700.1", de: "RPV", fr: "OAT", it: "OPT" },
  { sr: "711", de: "EntG", fr: "LEx", it: "LEspr" },
  { sr: "730.0", de: "EnG", fr: "LEne", it: "LEne" },
  { sr: "741.01", de: "SVG", fr: "LCR", it: "LCStr" },
  { sr: "741.013", de: "SKV", fr: "OCCR", it: "OCCS" },
  { sr: "741.11", de: "VRV", fr: "OCR", it: "ONC" },
  { sr: "741.21", de: "SSV", fr: "OSR", it: "OSStr" },
  { sr: "741.31", de: "VVV", fr: "OAV", it: "OAV" },
  { sr: "741.41", de: "VTS", fr: "OETV", it: "OETV" },
  { sr: "741.51", de: "VZV", fr: "OAC", it: "OAC" },
  { sr: "742.101", de: "EBG", fr: "LCdF", it: "Lferr" },
  { sr: "748.0", de: "LFG", fr: "LA", it: "LNA" },
  { sr: "748.131.1", de: "VIL", fr: "OSIA", it: "OSIA" },
  { sr: "784.10", de: "FMG", fr: "LTC", it: "LTC" },
  { sr: "784.101.1", de: "FDV", fr: "OST", it: "OST" },
  { sr: "784.101.2", de: "FAV", fr: "OIT", it: "OIT" },
  { sr: "812.121", de: "BetmG", fr: "LStup", it: "LStup" },
  { sr: "812.121.1", de: "BetmKV", fr: "OCStup", it: "OCStup" },
  { sr: "812.21", de: "HMG", fr: "LPTh", it: "LATer" },
  { sr: "812.212.1", de: "AMBV", fr: "OAMéd", it: "OAMed" },
  { sr: "812.212.21", de: "VAM", fr: "OMéd", it: "OM" },
  { sr: "812.213", de: "MepV", fr: "ODim", it: "ODmed" },
  { sr: "813.11", de: "ChemV", fr: "OChim", it: "OPChim" },
  { sr: "814.01", de: "USG", fr: "LPE", it: "LPAmb" },
  { sr: "814.011", de: "UVPV", fr: "OEIE", it: "OEIA" },
  { sr: "814.20", de: "GSchG", fr: "LEaux", it: "LPAc" },
  { sr: "814.201", de: "GSchV", fr: "OEaux", it: "OPAc" },
  { sr: "814.318.142.1", de: "LRV", fr: "OPair", it: "OIAt" },
  { sr: "814.41", de: "LSV", fr: "OPB", it: "OIF" },
  { sr: "814.600", de: "VVEA", fr: "OLED", it: "OPSR" },
  { sr: "814.610", de: "VeVA", fr: "OMoD", it: "OTRif" },
  { sr: "814.81", de: "ChemRRV", fr: "ORRChim", it: "ORRPChim" },
  { sr: "817.0", de: "LMG", fr: "LDAl", it: "LDerr" },
  { sr: "818.101", de: "EpG", fr: "LEp", it: "LEp" },
  { sr: "818.101.1", de: "EpV", fr: "OEp", it: "OEp" },
  { sr: "822.11", de: "ArG", fr: "LTr", it: "LL" },
  { sr: "822.111", de: "ArGV 1", fr: "OLT 1", it: "OLL 1" },
  { sr: "822.112", de: "ArGV 2", fr: "OLT 2", it: "OLL 2" },
  { sr: "822.113", de: "ArGV 3", fr: "OLT 3", it: "OLL 3" },
  { sr: "822.114", de: "ArGV 4", fr: "OLT 4", it: "OLL 4" },
  { sr: "822.115", de: "ArGV 5", fr: "OLT 5", it: "OLL 5" },
  { sr: "823.20", de: "EntsG", fr: "LDét", it: "LDist" },
  { sr: "830.1", de: "ATSG", fr: "LPGA", it: "LPGA" },
  { sr: "830.11", de: "ATSV", fr: "OPGA", it: "OPGA" },
  { sr: "831.10", de: "AHVG", fr: "LAVS", it: "LAVS" },
  { sr: "831.101", de: "AHVV", fr: "RAVS", it: "OAVS" },
  { sr: "831.111", de: "VFV", fr: "OAF", it: "OAF" },
  { sr: "831.20", de: "IVG", fr: "LAI", it: "LAI" },
  { sr: "831.201", de: "IVV", fr: "RAI", it: "OAI" },
  { sr: "831.30", de: "ELG", fr: "LPC", it: "LPC" },
  { sr: "831.301", de: "ELV", fr: "OPC-AVS/AI", it: "OPC-AVS/AI" },
  { sr: "831.40", de: "BVG", fr: "LPP", it: "LPP" },
  { sr: "831.42", de: "FZG", fr: "LFLP", it: "LFLP" },
  { sr: "831.425", de: "FZV", fr: "OLP", it: "OLP" },
  { sr: "831.441.1", de: "BVV 2", fr: "OPP 2", it: "OPP 2" },
  { sr: "831.461.3", de: "BVV 3", fr: "OPP 3", it: "OPP 3" },
  { sr: "832.10", de: "KVG", fr: "LAMal", it: "LAMal" },
  { sr: "832.102", de: "KVV", fr: "OAMal", it: "OAMal" },
  { sr: "832.104", de: "VKL", fr: "OCP", it: "OCPre" },
  { sr: "832.105", de: "VVK", fr: "OCA", it: "OTeA" },
  { sr: "832.112.31", de: "KLV", fr: "OPAS", it: "OPre" },
  { sr: "832.20", de: "UVG", fr: "LAA", it: "LAINF" },
  { sr: "832.202", de: "UVV", fr: "OLAA", it: "OAINF" },
  { sr: "833.1", de: "MVG", fr: "LAM", it: "LAM" },
  { sr: "833.11", de: "MVV", fr: "OAM", it: "OAM" },
  { sr: "834.1", de: "EOG", fr: "LAPG", it: "LIPG" },
  { sr: "834.11", de: "EOV", fr: "OAPG", it: "OIPG" },
  { sr: "836.2", de: "FamZG", fr: "LAFam", it: "LAFam" },
  { sr: "836.21", de: "FamZV", fr: "OAFam", it: "OAFami" },
  { sr: "837.0", de: "AVIG", fr: "LACI", it: "LADI" },
  { sr: "837.02", de: "AVIV", fr: "OACI", it: "OADI" },
  { sr: "921.0", de: "WaG", fr: "LFo", it: "LFo" },
  { sr: "921.01", de: "WaV", fr: "OFo", it: "OFo" },
  { sr: "935.61", de: "BGFA", fr: "LLCA", it: "LLCA" },
  { sr: "942.20", de: "PüG", fr: "LSPr", it: "LSPr" },
  { sr: "943.02", de: "BGBM", fr: "LMI", it: "LMI" },
  { sr: "946.51", de: "THG", fr: "LETC", it: "LOTC" },
  { sr: "946.512", de: "AkkBV", fr: "OAccD", it: "OAccD" },
  { sr: "950.1", de: "FIDLEG", fr: "LSFin", it: "LSerFi" },
  { sr: "950.11", de: "FIDLEV", fr: "OSFin", it: "OSerFi" },
  { sr: "951.131", de: "NBV", fr: "OBN", it: "OBN" },
  { sr: "951.31", de: "KAG", fr: "LPCC", it: "LICol" },
  { sr: "951.311", de: "KKV", fr: "OPCC", it: "OICol" },
  { sr: "951.312", de: "KKV-FINMA", fr: "OPC-FINMA", it: "OICol-FINMA" },
  { sr: "952.0", de: "BankG", fr: "LB", it: "LBCR" },
  { sr: "952.02", de: "BankV", fr: "OB", it: "OBCR" },
  { sr: "952.03", de: "ERV", fr: "OFR", it: "OFoP" },
  { sr: "954.1", de: "FINIG", fr: "LEFin", it: "LIsFi" },
  { sr: "954.11", de: "FINIV", fr: "OEFin", it: "OIsFi" },
  { sr: "955.0", de: "GwG", fr: "LBA", it: "LRD" },
  { sr: "955.033.0", de: "GwV-FINMA", fr: "OBA-FINMA", it: "ORD-FINMA" },
  { sr: "956.1", de: "FINMAG", fr: "LFINMA", it: "LFINMA" },
  { sr: "956.122", de: "FINMA-GebV", fr: "Oém-FINMA", it: "Oem-FINMA" },
  { sr: "957.1", de: "BEG", fr: "LTI", it: "LTCo" },
  { sr: "958.1", de: "FinfraG", fr: "LIMF", it: "LInFi" },
  { sr: "958.11", de: "FinfraV", fr: "OIMF", it: "OInFi" },
  { sr: "958.111", de: "FinfraV-FINMA", fr: "OIMF-FINMA", it: "OInFi-FINMA" },
  { sr: "961.01", de: "VAG", fr: "LSA", it: "LSA" },
  { sr: "961.011", de: "AVO", fr: "OS", it: "OS" },
];
